### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by igerko** [aldryn/aldryn-newsblog#444] opened 2017-02-10 13:00 UTC
It's imposible to use this plugin with Django 1.10, I'm getting error bellow. When I use Django 1.9, everything is working fine.

`django.core.exceptions.FieldError: 'content' cannot be specified for Article model form as it is a non-editable field`

**Comment by FabrizioA** [comment] 2017-03-24 14:47
I've the same issue 😢

**Comment by bartmika** [comment] 2017-03-24 23:05
+1

**Comment by FabrizioA** [comment] 2017-03-27 11:15
I had to downgrade Django to 1.9.x to fix it... :'(

**Comment by rodolfomartinez** [comment] 2017-04-04 15:28
massive +1

**Comment by FabrizioA** [comment] 2017-04-13 15:23
supermassive +1

**Comment by evildmp** [comment] 2017-04-17 08:12
We'd be grateful for any community help to get this up-to-date. It's an open-source project that relies on the contributions that developers (whether as individuals or from companies that use the software) are able to make to it.

If you'd be able to help, please send a message to the [django CMS Developers list](https://groups.google.com/forum/#!topic/django-cms-developers/8841mspjU_I) expressing your interest.

I'm closing this as a duplicate of https://github.com/aldryn/aldryn-newsblog/issues/440.

**Closed by evildmp** 2017-04-17 08:12 UTC

**Comment by artforlife** [comment] 2017-09-19 16:34
Has anyone been able to resolve this? I am just seeing this error for the first time right now.

**Comment by LRH539** [comment] 2017-09-19 16:57
Are you using the version from the master branch + Django CMS 1.10 ? I think I fixed this by simply using the version from github.
